//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadUSB_Firewall.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdminRights {
            get {
                return ((bool)(this["AdminRights"]));
            }
            set {
                this["AdminRights"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowPopupMessages {
            get {
                return ((bool)(this["AllowPopupMessages"]));
            }
            set {
                this["AllowPopupMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockUSBDevices {
            get {
                return ((bool)(this["BlockUSBDevices"]));
            }
            set {
                this["BlockUSBDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TerminateProcess {
            get {
                return ((bool)(this["TerminateProcess"]));
            }
            set {
                this["TerminateProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Is64BitOS {
            get {
                return ((bool)(this["Is64BitOS"]));
            }
            set {
                this["Is64BitOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InitialNetworkAdapters {
            get {
                return ((int)(this["InitialNetworkAdapters"]));
            }
            set {
                this["InitialNetworkAdapters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InitialKeyboardConnected {
            get {
                return ((int)(this["InitialKeyboardConnected"]));
            }
            set {
                this["InitialKeyboardConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InitialPointingDevices {
            get {
                return ((int)(this["InitialPointingDevices"]));
            }
            set {
                this["InitialPointingDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tweak_BlockAll {
            get {
                return ((bool)(this["Tweak_BlockAll"]));
            }
            set {
                this["Tweak_BlockAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tweak_BlockStorage {
            get {
                return ((bool)(this["Tweak_BlockStorage"]));
            }
            set {
                this["Tweak_BlockStorage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tweak_BlockMice {
            get {
                return ((bool)(this["Tweak_BlockMice"]));
            }
            set {
                this["Tweak_BlockMice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tweak_BlockKeyboards {
            get {
                return ((bool)(this["Tweak_BlockKeyboards"]));
            }
            set {
                this["Tweak_BlockKeyboards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BadUSB-Software-Firewall")]
        public string MyTitle {
            get {
                return ((string)(this["MyTitle"]));
            }
            set {
                this["MyTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Detect_USBChanges {
            get {
                return ((bool)(this["Detect_USBChanges"]));
            }
            set {
                this["Detect_USBChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticRemoveofDriver {
            get {
                return ((bool)(this["AutomaticRemoveofDriver"]));
            }
            set {
                this["AutomaticRemoveofDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedSettings {
            get {
                return ((bool)(this["AdvancedSettings"]));
            }
            set {
                this["AdvancedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProtectiveFunction {
            get {
                return ((bool)(this["ProtectiveFunction"]));
            }
            set {
                this["ProtectiveFunction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AppExitKeyboards {
            get {
                return ((int)(this["AppExitKeyboards"]));
            }
            set {
                this["AppExitKeyboards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AppExitPointingDevices {
            get {
                return ((int)(this["AppExitPointingDevices"]));
            }
            set {
                this["AppExitPointingDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AppExitNetworkAdapters {
            get {
                return ((int)(this["AppExitNetworkAdapters"]));
            }
            set {
                this["AppExitNetworkAdapters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SafeMode {
            get {
                return ((bool)(this["SafeMode"]));
            }
            set {
                this["SafeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Auto_StartKeylogger {
            get {
                return ((bool)(this["Auto_StartKeylogger"]));
            }
            set {
                this["Auto_StartKeylogger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StopApplication {
            get {
                return ((bool)(this["StopApplication"]));
            }
            set {
                this["StopApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContinueApplication {
            get {
                return ((bool)(this["ContinueApplication"]));
            }
            set {
                this["ContinueApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotifyWhitelist {
            get {
                return ((bool)(this["NotifyWhitelist"]));
            }
            set {
                this["NotifyWhitelist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowOnlyMassStorage {
            get {
                return ((bool)(this["AllowOnlyMassStorage"]));
            }
            set {
                this["AllowOnlyMassStorage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DetectPortChange {
            get {
                return ((bool)(this["DetectPortChange"]));
            }
            set {
                this["DetectPortChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProhibitPortChange {
            get {
                return ((bool)(this["ProhibitPortChange"]));
            }
            set {
                this["ProhibitPortChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockNewKeyboards {
            get {
                return ((bool)(this["BlockNewKeyboards"]));
            }
            set {
                this["BlockNewKeyboards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockIdenticalWhitelist {
            get {
                return ((bool)(this["BlockIdenticalWhitelist"]));
            }
            set {
                this["BlockIdenticalWhitelist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockNewNetworkAdapter {
            get {
                return ((bool)(this["BlockNewNetworkAdapter"]));
            }
            set {
                this["BlockNewNetworkAdapter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockNewHID {
            get {
                return ((bool)(this["BlockNewHID"]));
            }
            set {
                this["BlockNewHID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockNewMassStorage {
            get {
                return ((bool)(this["BlockNewMassStorage"]));
            }
            set {
                this["BlockNewMassStorage"] = value;
            }
        }
    }
}
